/*
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui.parts;

import java.beans.Beans;
import javax.swing.DefaultComboBoxModel;
import org.openide.util.Lookup;
import se.trixon.sabas.core.PkgManager;
import se.trixon.sabas.core.api.Bridge;

/**
 *
 * @author Patrik Karlström <patrik@trixon.se>
 */
public class BridgeSelectorPanel extends javax.swing.JPanel {

    private PkgManager mPkgManager;

    /**
     * Creates new form BridgeSelectorPanel
     */
    public BridgeSelectorPanel() {
        initComponents();
        if (!Beans.isDesignTime()) {
            mPkgManager = PkgManager.getInstance();
            init();
        }
    }

    private void init() {
        bridgeComboBox.setRenderer(new BridgeSelectorRenderer());
        Lookup.getDefault().lookupResult(Bridge.class).addLookupListener(lookupEvent -> {
            updateBridges();
        });
        updateBridges();

        bridgeComboBox.setSelectedItem(mPkgManager.getBridge());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bridgeLabel = new javax.swing.JLabel();
        bridgeComboBox = new javax.swing.JComboBox<>();

        org.openide.awt.Mnemonics.setLocalizedText(bridgeLabel, org.openide.util.NbBundle.getMessage(BridgeSelectorPanel.class, "BridgeSelectorPanel.bridgeLabel.text")); // NOI18N

        bridgeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bridgeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bridgeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bridgeComboBox, 0, 394, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bridgeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bridgeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bridgeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bridgeComboBoxActionPerformed
        mPkgManager.setBridge((Bridge) bridgeComboBox.getSelectedItem());
    }//GEN-LAST:event_bridgeComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Bridge> bridgeComboBox;
    private javax.swing.JLabel bridgeLabel;
    // End of variables declaration//GEN-END:variables

    private void updateBridges() {
        var bridges = Lookup.getDefault().lookupAll(Bridge.class).stream().toArray(Bridge[]::new);
        var comboBoxCheckModel = new DefaultComboBoxModel<Bridge>(bridges);
        bridgeComboBox.setModel(comboBoxCheckModel);
    }
}
