/* 
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui.parts;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import se.trixon.sabas.core.api.Bridge;

/**
 *
 * @author Patrik Karlström <patrik@trixon.se>
 */
public class BridgeSelectorRenderer extends javax.swing.JPanel implements ListCellRenderer<Bridge> {

    /**
     * Creates new form BridgeListCell
     */
    public BridgeSelectorRenderer() {
        initComponents();
    }

    @Override
    public Component getListCellRendererComponent(JList<? extends Bridge> list, Bridge bridge, int index, boolean isSelected, boolean cellHasFocus) {
        if (isSelected) {
            setBackground(list.getSelectionBackground());
            nameLabel.setForeground(list.getSelectionForeground());
            groupLabel.setForeground(list.getSelectionForeground());
            descLabel.setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            nameLabel.setForeground(list.getForeground());
            groupLabel.setForeground(Color.GRAY);
            descLabel.setForeground(Color.DARK_GRAY);
        }

        if (bridge != null) {
            nameLabel.setText(bridge.getName());
            groupLabel.setText("[" + bridge.getSupports() + "]");
            descLabel.setText(bridge.getDescription());
        } else {
            nameLabel.setText("");
            groupLabel.setText("");
            descLabel.setText("");
        }

        setEnabled(list.isEnabled());
        setFont(list.getFont());
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        nameLabel.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(BridgeSelectorRenderer.class, "BridgeSelectorRenderer.nameLabel.text")); // NOI18N
        add(nameLabel);

        org.openide.awt.Mnemonics.setLocalizedText(groupLabel, org.openide.util.NbBundle.getMessage(BridgeSelectorRenderer.class, "BridgeSelectorRenderer.groupLabel.text")); // NOI18N
        add(groupLabel);

        org.openide.awt.Mnemonics.setLocalizedText(descLabel, org.openide.util.NbBundle.getMessage(BridgeSelectorRenderer.class, "BridgeSelectorRenderer.descLabel.text")); // NOI18N
        add(descLabel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
