/* 
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui.parts;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import se.trixon.sabas.core.api.Pkg;

/**
 *
 * @author Patrik Karlström <patrik@trixon.se>
 */
public class PkgRenderer extends javax.swing.JPanel implements ListCellRenderer<Pkg> {

    /**
     * Creates new form PkgRenderer
     */
    public PkgRenderer() {
        initComponents();
    }

    @Override
    public Component getListCellRendererComponent(JList<? extends Pkg> list, Pkg pkg, int index, boolean isSelected, boolean cellHasFocus) {
        Color bg = isSelected ? list.getSelectionBackground() : list.getBackground();
        Color fg = isSelected ? list.getSelectionForeground() : list.getForeground();
        setBackground(bg);

        jLabel1.setForeground(fg);
        jLabel2.setForeground(isSelected ? fg : Color.GRAY);
        jLabel3.setForeground(isSelected ? fg : Color.DARK_GRAY);

        if (pkg != null) {
            jLabel1.setText(pkg.getName());
            jLabel2.setText(pkg.getSummary());
            jLabel3.setText(pkg.getVersion());
        }

        setEnabled(list.isEnabled());
        setFont(list.getFont());
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PkgRenderer.class, "PkgRenderer.jLabel1.text")); // NOI18N
        add(jLabel1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PkgRenderer.class, "PkgRenderer.jLabel2.text")); // NOI18N
        add(jLabel2);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PkgRenderer.class, "PkgRenderer.jLabel3.text")); // NOI18N
        add(jLabel3);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
