/*
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui.parts;

import java.awt.Component;
import java.awt.Font;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import se.trixon.almond.util.GraphicsHelper;
import se.trixon.sabas.core.api.Pkg;

/**
 *
 * @author Patrik Karlström <patrik@trixon.se>
 */
public class PkgRenderer extends javax.swing.JPanel implements ListCellRenderer<Pkg> {

    /**
     * Creates new form PkgRenderer
     */
    public PkgRenderer() {
        initComponents();
    }

    @Override
    public Component getListCellRendererComponent(JList<? extends Pkg> list, Pkg pkg, int index, boolean isSelected, boolean cellHasFocus) {
        var bg = isSelected ? list.getSelectionBackground() : (index & 1) == 0 ? list.getBackground() : GraphicsHelper.getZebraStripe(list.getBackground());
        var fg = isSelected ? list.getSelectionForeground() : list.getForeground();
        setBackground(bg);
        label1.setForeground(fg);
        label2.setForeground(fg);
        label3.setForeground(fg);

        if (pkg != null) {
            label1.setText(pkg.getName());
            label2.setText(pkg.getVersion());
            label3.setText(pkg.getSummary());
        }

        setEnabled(list.isEnabled());
        label1.setFont(list.getFont().deriveFont(Font.BOLD));
        label3.setFont(list.getFont().deriveFont(Font.ITALIC));
        setFont(list.getFont());

        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(label1, org.openide.util.NbBundle.getMessage(PkgRenderer.class, "PkgRenderer.label1.text")); // NOI18N
        add(label1);

        org.openide.awt.Mnemonics.setLocalizedText(label2, org.openide.util.NbBundle.getMessage(PkgRenderer.class, "PkgRenderer.label2.text")); // NOI18N
        add(label2);

        org.openide.awt.Mnemonics.setLocalizedText(label3, org.openide.util.NbBundle.getMessage(PkgRenderer.class, "PkgRenderer.label3.text")); // NOI18N
        add(label3);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    // End of variables declaration//GEN-END:variables
}
