/* 
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui;

import java.util.HashSet;
import java.util.Set;
import java.util.function.Function;
import javax.swing.DefaultListModel;
import se.trixon.almond.util.swing.SwingHelper;
import se.trixon.sabas.Sabas;
import se.trixon.sabas.api.DictionarySection;
import se.trixon.sabas.api.Pkg;
import se.trixon.sabas.api.PkgDictionary;
import se.trixon.sabas.core.Filter;
import se.trixon.sabas.core.FilterManager;
import se.trixon.sabas.core.PkgManager;
import se.trixon.sabas.ui.parts.ZebraListCellRenderer;

/**
 * Top component which displays something.
 */
public abstract class BaseFilterTopComponent extends BaseTopComponent implements Filter {

    protected final Set<Integer> mSelectedIds = new HashSet<>();
    private final DictionarySection mDictionarySection;
    protected final FilterManager mFilterManager = FilterManager.getInstance();
    private Function<Pkg, Integer> mFilterFunction;

    public BaseFilterTopComponent(DictionarySection dictionarySection, Function<Pkg, Integer> filterFunction) {
        mDictionarySection = dictionarySection;
        mFilterFunction = filterFunction;
        mFilterManager.add(this);
        initComponents();
        list.setCellRenderer(new ZebraListCellRenderer());
        initListeners();
    }

    @Override
    public boolean filter(Pkg pkg) {
        return mSelectedIds.isEmpty() || mSelectedIds.contains(-1) || mSelectedIds.contains(mFilterFunction.apply(pkg));
    }

    @Override
    public void reset() {
        list.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        list = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        scrollPane.setViewportView(list);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList list;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    private void initListeners() {
        Sabas.getGlobalState().addListener(gsce -> {
            populateList();
        }, PkgManager.KEY_ALL_ITEMS);

        Sabas.getGlobalState().addListener(gsce -> {
            var enabled = !gsce.<Boolean>getValue();
            SwingHelper.enableComponents(this, enabled);
            //makeBusy(!enabled);
        }, PkgManager.KEY_TASK_RUNNING);

        list.addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {
                var selectedTexts = list.getSelectedValuesList();
                mSelectedIds.clear();
                for (var text : selectedTexts) {
                    int id = PkgDictionary.getInstance().getId(mDictionarySection, (String) text);
                    if (id == -1) {
                        break;
                    }
                    mSelectedIds.add(id);
                }
                mFilterManager.requestFiltering();
            }
        });
    }

    private void populateList() {
        var model = new DefaultListModel<String>();
        model.addElement("*");

        var allItems = PkgDictionary.getInstance().getAllValuesSorted(mDictionarySection);
        model.addAll(allItems);

        list.setModel(model);
        list.setSelectedIndex(0);
    }

}
