/* 
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui;

import javafx.collections.ListChangeListener;
import javafx.collections.ObservableList;
import javax.swing.AbstractListModel;
import javax.swing.SwingUtilities;
import se.trixon.sabas.core.Options;
import se.trixon.sabas.core.PkgManager;
import se.trixon.sabas.core.api.Pkg;
import se.trixon.sabas.ui.parts.PkgRenderer;

/**
 *
 * @author Patrik Karlström <patrik@trixon.se>
 */
public class BrowserPanel extends javax.swing.JPanel {

    private final Options mOptions = Options.getInstance();
    private final PkgManager mPkgManager = PkgManager.getInstance();
    private final PkgListModel mPkgListModel;

    /**
     * Creates new form BrowserPanel
     */
    public BrowserPanel() {
        initComponents();
        initListeners();
        mPkgListModel = new PkgListModel(mPkgManager.getFilteredItems());
        packagesList.setModel(mPkgListModel);
        packagesList.setCellRenderer(new PkgRenderer());

        mPkgManager.populatePackages();
    }

    public void postCreate() {
        restoreDividerPositions();
    }

    private void displayPackageInfo(Pkg pkg) {
        if (pkg == null) {
            nameLabel.setText("");
        } else {
            nameLabel.setText(pkg.getName());

        }
    }

    private void initListeners() {
        Helper.setupDividerMouseListener(splitPane, Options.KEY_UI_SPLIT_POS_CENTER);
        mPkgManager.getFilteredItems().addListener((ListChangeListener.Change<? extends Pkg> c) -> {
            SwingUtilities.invokeLater(() -> {
                if (mPkgListModel != null) {
                    mPkgListModel.updateData();
                }
            });
        });

        mPkgManager.selectedPkgProperty().addListener((p, o, n) -> {
            displayPackageInfo(n);
        });
    }

    private void restoreDividerPositions() {
        int mainPos = mOptions.getInt(Options.KEY_UI_SPLIT_POS_CENTER);
        if (mainPos == 0) {
            splitPane.setDividerLocation(0.25);
        } else {
            splitPane.setDividerLocation(mainPos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        packagesScrollPane = new javax.swing.JScrollPane();
        packagesList = new javax.swing.JList<>();
        infoPanel = new javax.swing.JPanel();
        infoHeaderPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        infoTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        packagesScrollPane.setMinimumSize(new java.awt.Dimension(250, 23));
        packagesScrollPane.setPreferredSize(new java.awt.Dimension(300, 260));

        packagesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        packagesList.setMinimumSize(new java.awt.Dimension(300, 160));
        packagesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                packagesListValueChanged(evt);
            }
        });
        packagesScrollPane.setViewportView(packagesList);

        splitPane.setLeftComponent(packagesScrollPane);

        infoPanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, "NAME"); // NOI18N

        javax.swing.GroupLayout infoHeaderPanelLayout = new javax.swing.GroupLayout(infoHeaderPanel);
        infoHeaderPanel.setLayout(infoHeaderPanelLayout);
        infoHeaderPanelLayout.setHorizontalGroup(
            infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addContainerGap(817, Short.MAX_VALUE))
        );
        infoHeaderPanelLayout.setVerticalGroup(
            infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        infoPanel.add(infoHeaderPanel, java.awt.BorderLayout.CENTER);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 812, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        infoTabbedPane.addTab("tab1", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        infoTabbedPane.addTab(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        infoPanel.add(infoTabbedPane, java.awt.BorderLayout.PAGE_END);

        splitPane.setRightComponent(infoPanel);

        add(splitPane);
    }// </editor-fold>//GEN-END:initComponents

    private void packagesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_packagesListValueChanged
        if (!evt.getValueIsAdjusting()) {
            mPkgManager.setSelectedPkg(packagesList.getSelectedValue());
        }
    }//GEN-LAST:event_packagesListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel infoHeaderPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JTabbedPane infoTabbedPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JList<Pkg> packagesList;
    private javax.swing.JScrollPane packagesScrollPane;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

    private static class PkgListModel extends AbstractListModel<Pkg> {

        private final ObservableList<? extends Pkg> sourceList;

        public PkgListModel(ObservableList<Pkg> filteredItems) {
            this.sourceList = filteredItems;
        }

        public void updateData() {
            fireContentsChanged(this, 0, Math.max(0, getSize() - 1));
        }

        @Override
        public int getSize() {
            return sourceList.size();
        }

        @Override
        public Pkg getElementAt(int index) {
            return sourceList.get(index);
        }
    }
}
