/*
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui;

import java.awt.CardLayout;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javafx.collections.ListChangeListener;
import javafx.collections.ObservableList;
import javax.swing.AbstractListModel;
import javax.swing.SwingUtilities;
import se.trixon.sabas.core.Options;
import se.trixon.sabas.core.PkgManager;
import se.trixon.sabas.core.api.Pkg;
import se.trixon.sabas.ui.parts.PkgRenderer;

/**
 *
 * @author Patrik Karlström <patrik@trixon.se>
 */
public class BrowserPanel extends javax.swing.JPanel {

    private final Options mOptions = Options.getInstance();
    private final PkgManager mPkgManager = PkgManager.getInstance();
    private final PkgListModel mPkgListModel;
    private DateTimeFormatter mFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")
            .withZone(ZoneId.systemDefault());

    /**
     * Creates new form BrowserPanel
     */
    public BrowserPanel() {
        initComponents();
        initListeners();
        mPkgListModel = new PkgListModel(mPkgManager.getFilteredItems());
        packagesList.setModel(mPkgListModel);
        packagesList.setCellRenderer(new PkgRenderer());

        mPkgManager.populatePackages();
    }

    public void postCreate() {
        restoreDividerPositions();
    }

    private void displayPackageInfo(Pkg pkg) {
        var cardLayout = (CardLayout) (cardPanel.getLayout());
        cardLayout.show(cardPanel, pkg == null ? "empty" : "info");

        if (pkg != null) {
            idLabel.setText(pkg.getId());
            nameLabel.setText(pkg.getName());
            summaryLabel.setText(pkg.getSummary());
            descriptionLogPanel.clear();
            descriptionLogPanel.println(pkg.getDescription());
            descriptionLogPanel.scrollToTop();
            versionLabel.setText(pkg.getVersion());
            licenseLabel.setText(pkg.getLicense());
            sizeDownloadLabel.setText(formatSize(pkg.getSizeDownload()));
            sizeInstallLabel.setText(formatSize(pkg.getSizeInstall()));
            vendorLabel.setText(pkg.getVendor());
            urlLabel.setText(pkg.getUrl());
            urlLabel.setUri(pkg.getUrl());
            repositoryLabel.setText(pkg.getRepository());
            packagerLabel.setText(pkg.getPackager());
            releaseLabel.setText(pkg.getRelease());
            archLabel.setText(pkg.getArch());
            buildTimeLabel.setText(mFormatter.format(pkg.getTimeBuildInstant()));
            installedTimeLabel.setText(mFormatter.format(pkg.getTimeInstalledInstant()));
        }
    }

    private void initListeners() {
        Helper.setupDividerMouseListener(splitPane, Options.KEY_UI_SPLIT_POS_CENTER);

        mPkgManager.getFilteredItems().addListener((ListChangeListener.Change<? extends Pkg> c) -> {
            SwingUtilities.invokeLater(() -> {
                updateFooter();
                if (mPkgListModel != null) {
                    mPkgListModel.updateData();
                    if (mPkgListModel.getSize() > 0) {
                        packagesList.setSelectedIndex(0);
                    }
                }
            });
        });

        mPkgManager.selectedPkgProperty().addListener((p, o, n) -> {
            displayPackageInfo(n);
        });
    }

    private void updateFooter() {
        var selected = "";
        var selectedIndex = packagesList.getSelectedIndex();
        if (selectedIndex != -1) {
            selected = "@%,d/".formatted(selectedIndex + 1);
        }
        footerLabel.setText("%s%,d/%,d".formatted(
                selected,
                mPkgManager.getFilteredItems().size(),
                mPkgManager.getAllItems().size()
        ));
    }

    private void restoreDividerPositions() {
        int mainPos = mOptions.getInt(Options.KEY_UI_SPLIT_POS_CENTER);
        if (mainPos == 0) {
            splitPane.setDividerLocation(0.25);
        } else {
            splitPane.setDividerLocation(mainPos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        listPanel = new javax.swing.JPanel();
        packagesScrollPane = new javax.swing.JScrollPane();
        packagesList = new javax.swing.JList<>();
        footerLabel = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        emptyCardPanel = new javax.swing.JPanel();
        infoCardPanel = new javax.swing.JPanel();
        infoHeaderPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        summaryLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        licenseLabel = new javax.swing.JLabel();
        sizeInstallHeaderLabel = new javax.swing.JLabel();
        sizeInstallLabel = new javax.swing.JLabel();
        sizeDownloadHeaderLabel = new javax.swing.JLabel();
        sizeDownloadLabel = new javax.swing.JLabel();
        vendorLabel = new javax.swing.JLabel();
        urlLabel = new se.trixon.almond.util.swing.UriLabel();
        repositoryLabel = new javax.swing.JLabel();
        packagerLabel = new javax.swing.JLabel();
        releaseLabel = new javax.swing.JLabel();
        archLabel = new javax.swing.JLabel();
        installedTimeLabel = new javax.swing.JLabel();
        buildTimeLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        infoTabbedPane = new javax.swing.JTabbedPane();
        descriptionLogPanel = new se.trixon.almond.util.swing.LogPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        listPanel.setLayout(new java.awt.BorderLayout());

        packagesScrollPane.setMinimumSize(new java.awt.Dimension(250, 23));
        packagesScrollPane.setPreferredSize(new java.awt.Dimension(300, 260));

        packagesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        packagesList.setMinimumSize(new java.awt.Dimension(300, 160));
        packagesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                packagesListValueChanged(evt);
            }
        });
        packagesScrollPane.setViewportView(packagesList);

        listPanel.add(packagesScrollPane, java.awt.BorderLayout.CENTER);

        footerLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(footerLabel, "0/0"); // NOI18N
        listPanel.add(footerLabel, java.awt.BorderLayout.SOUTH);

        splitPane.setLeftComponent(listPanel);

        cardPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout emptyCardPanelLayout = new javax.swing.GroupLayout(emptyCardPanel);
        emptyCardPanel.setLayout(emptyCardPanelLayout);
        emptyCardPanelLayout.setHorizontalGroup(
            emptyCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        emptyCardPanelLayout.setVerticalGroup(
            emptyCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        cardPanel.add(emptyCardPanel, "empty");

        infoCardPanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, "NAME"); // NOI18N
        nameLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.nameLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(summaryLabel, "SUMMARY"); // NOI18N
        summaryLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.summaryLabel.toolTipText")); // NOI18N

        versionLabel.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(versionLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.versionLabel.text")); // NOI18N
        versionLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.versionLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(licenseLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.licenseLabel.text")); // NOI18N
        licenseLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.licenseLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sizeInstallHeaderLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.sizeInstallHeaderLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sizeInstallLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.sizeInstallLabel.text")); // NOI18N
        sizeInstallLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.sizeInstallLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sizeDownloadHeaderLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.sizeDownloadHeaderLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sizeDownloadLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.sizeDownloadLabel.text")); // NOI18N
        sizeDownloadLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.sizeDownloadLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(vendorLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.vendorLabel.text")); // NOI18N
        vendorLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.vendorLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(urlLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.urlLabel.text")); // NOI18N
        urlLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.urlLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(repositoryLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.repositoryLabel.text")); // NOI18N
        repositoryLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.repositoryLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(packagerLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.packagerLabel.text")); // NOI18N
        packagerLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.packagerLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(releaseLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.releaseLabel.text")); // NOI18N
        releaseLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.releaseLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(archLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.archLabel.text")); // NOI18N
        archLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.archLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(installedTimeLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.installedTimeLabel.text")); // NOI18N
        installedTimeLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.installedTimeLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buildTimeLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.buildTimeLabel.text")); // NOI18N
        buildTimeLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.buildTimeLabel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(idLabel, org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.idLabel.text")); // NOI18N
        idLabel.setToolTipText(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.idLabel.toolTipText")); // NOI18N

        javax.swing.GroupLayout infoHeaderPanelLayout = new javax.swing.GroupLayout(infoHeaderPanel);
        infoHeaderPanel.setLayout(infoHeaderPanelLayout);
        infoHeaderPanelLayout.setHorizontalGroup(
            infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(versionLabel))
                    .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                        .addComponent(licenseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sizeInstallLabel))
                    .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                        .addComponent(summaryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                        .addComponent(sizeInstallHeaderLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoHeaderPanelLayout.createSequentialGroup()
                        .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sizeDownloadLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoHeaderPanelLayout.createSequentialGroup()
                        .addComponent(vendorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sizeDownloadHeaderLabel))
                    .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                        .addComponent(packagerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(archLabel))
                    .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                        .addComponent(repositoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(releaseLabel))
                    .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(installedTimeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(buildTimeLabel)))
                .addContainerGap())
        );
        infoHeaderPanelLayout.setVerticalGroup(
            infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(versionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summaryLabel)
                    .addComponent(sizeInstallHeaderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseLabel)
                    .addComponent(sizeInstallLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeDownloadHeaderLabel)
                    .addComponent(vendorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeDownloadLabel)
                    .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repositoryLabel)
                    .addComponent(releaseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packagerLabel)
                    .addComponent(archLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(installedTimeLabel)
                    .addComponent(buildTimeLabel)
                    .addComponent(idLabel))
                .addContainerGap())
        );

        infoCardPanel.add(infoHeaderPanel, java.awt.BorderLayout.NORTH);

        infoTabbedPane.setMinimumSize(new java.awt.Dimension(80, 166));
        infoTabbedPane.setPreferredSize(new java.awt.Dimension(698, 150));
        infoTabbedPane.addTab(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.descriptionLogPanel.TabConstraints.tabTitle"), descriptionLogPanel); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        infoTabbedPane.addTab(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        infoTabbedPane.addTab(org.openide.util.NbBundle.getMessage(BrowserPanel.class, "BrowserPanel.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        infoCardPanel.add(infoTabbedPane, java.awt.BorderLayout.CENTER);

        cardPanel.add(infoCardPanel, "info");

        splitPane.setRightComponent(cardPanel);

        add(splitPane);
    }// </editor-fold>//GEN-END:initComponents

    private void packagesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_packagesListValueChanged
        if (!evt.getValueIsAdjusting()) {
            mPkgManager.setSelectedPkg(packagesList.getSelectedValue());
            updateFooter();
        }
    }//GEN-LAST:event_packagesListValueChanged

    private String formatSize(long bytes) {
        if (bytes <= 0) {
            return "0 B";
        }

        final long KiB = 1024L;
        final long MiB = KiB * 1024L;
        final long GiB = MiB * 1024L;

        if (bytes >= GiB) {
            return String.format("%.2f GiB", (double) bytes / GiB);
        } else if (bytes >= MiB) {
            return String.format("%.2f MiB", (double) bytes / MiB);
        } else if (bytes >= KiB) {
            return String.format("%.2f KiB", (double) bytes / KiB);
        } else {
            return bytes + " B";
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel archLabel;
    private javax.swing.JLabel buildTimeLabel;
    private javax.swing.JPanel cardPanel;
    private se.trixon.almond.util.swing.LogPanel descriptionLogPanel;
    private javax.swing.JPanel emptyCardPanel;
    private javax.swing.JLabel footerLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel infoCardPanel;
    private javax.swing.JPanel infoHeaderPanel;
    private javax.swing.JTabbedPane infoTabbedPane;
    private javax.swing.JLabel installedTimeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel licenseLabel;
    private javax.swing.JPanel listPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel packagerLabel;
    private javax.swing.JList<Pkg> packagesList;
    private javax.swing.JScrollPane packagesScrollPane;
    private javax.swing.JLabel releaseLabel;
    private javax.swing.JLabel repositoryLabel;
    private javax.swing.JLabel sizeDownloadHeaderLabel;
    private javax.swing.JLabel sizeDownloadLabel;
    private javax.swing.JLabel sizeInstallHeaderLabel;
    private javax.swing.JLabel sizeInstallLabel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel summaryLabel;
    private se.trixon.almond.util.swing.UriLabel urlLabel;
    private javax.swing.JLabel vendorLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables

    private static class PkgListModel extends AbstractListModel<Pkg> {

        private final ObservableList<? extends Pkg> sourceList;

        public PkgListModel(ObservableList<Pkg> filteredItems) {
            this.sourceList = filteredItems;
        }

        public void updateData() {
            fireContentsChanged(this, 0, Math.max(0, getSize() - 1));
        }

        @Override
        public int getSize() {
            return sourceList.size();
        }

        @Override
        public Pkg getElementAt(int index) {
            return sourceList.get(index);
        }
    }
}
