/* 
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui;

import java.awt.Component;
import java.awt.Container;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.Actions;
import org.openide.util.NbBundle.Messages;
import org.openide.util.actions.Presenter;
import org.openide.windows.TopComponent;
import se.trixon.sabas.api.DictionarySection;
import se.trixon.sabas.api.Pkg;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//se.trixon.sabas.ui//Filter//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "FilterTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "left", openAtStartup = true)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_FilterAction",
        preferredID = "FilterTopComponent"
)
@Messages({
    "CTL_FilterAction=Text"
})
public final class FilterTextTopComponent extends BaseFilterTopComponent {

    public FilterTextTopComponent() {
        super(DictionarySection.ARCH, pkg -> -1);//DUMMY
        initComponents();
        setName(Bundle.CTL_FilterAction());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);

        initListeners();
//        initQuickSearch();
    }

    private JTextArea findFirstTextArea(Container container) {
        if (container == null) {
            return null;
        }

        // Loopa igenom alla direkta barn till komponenten
        for (Component child : container.getComponents()) {

            // Om barnet är en JTextArea, har vi hittat rätt!
            if (child instanceof JTextArea) {
                return (JTextArea) child;
            }

            // Om barnet i sin tur är en container (t.ex. en JPanel), sök vidare djupare i trädet
            if (child instanceof Container) {
                JTextArea found = findFirstTextArea((Container) child);
                if (found != null) {
                    return found; // Returnera direkt om den hittades djupare ner
                }
            }
        }

        return null; // Ingen JTextArea hittades i denna gren
    }

    @Override
    public boolean filter(Pkg pkg) {
        return true;
    }

    @Override
    public void reset() {
        filterTextField.setText("");
        List.of(
                summaryCheckBox,
                descriptionCheckBox)
                .forEach(cb -> cb.setSelected(false));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterTextField = new javax.swing.JTextField();
        summaryCheckBox = new javax.swing.JCheckBox();
        descriptionCheckBox = new javax.swing.JCheckBox();
        resetButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(summaryCheckBox, org.openide.util.NbBundle.getMessage(FilterTextTopComponent.class, "FilterTextTopComponent.summaryCheckBox.text")); // NOI18N
        summaryCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryCheckBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(descriptionCheckBox, org.openide.util.NbBundle.getMessage(FilterTextTopComponent.class, "FilterTextTopComponent.descriptionCheckBox.text")); // NOI18N
        descriptionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionCheckBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(resetButton, org.openide.util.NbBundle.getMessage(FilterTextTopComponent.class, "FilterTextTopComponent.resetButton.text")); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(summaryCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(descriptionCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summaryCheckBox)
                    .addComponent(descriptionCheckBox)
                    .addComponent(resetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initQuickSearch() {
        var quickSearchAction = Actions.forID("Edit", "org.netbeans.modules.quicksearch.QuickSearchAction");
        if (quickSearchAction instanceof Presenter.Toolbar toolbar) {
            JComponent component = (JComponent) toolbar.getToolbarPresenter();
//            panel.add(component, BorderLayout.CENTER);
            var textArea = findFirstTextArea(component);
            if (textArea != null) {
                textArea.getDocument().addDocumentListener(new DocumentListener() {
                    @Override
                    public void changedUpdate(DocumentEvent e) {
                        qqq();
                    }

                    @Override
                    public void insertUpdate(DocumentEvent e) {
                        qqq();
                    }

                    @Override
                    public void removeUpdate(DocumentEvent e) {
                        qqq();
                    }

                    private void qqq() {
                        if (textArea.getText().isEmpty()) {
                            mFilterManager.setText("");
                            mFilterManager.requestFiltering();
                        }
                    }
                });
            }
        }
    }

    private void summaryCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryCheckBoxActionPerformed
        requestFiltering();
    }//GEN-LAST:event_summaryCheckBoxActionPerformed

    private void descriptionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionCheckBoxActionPerformed
        requestFiltering();
    }//GEN-LAST:event_descriptionCheckBoxActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        mFilterManager.reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox descriptionCheckBox;
    private javax.swing.JTextField filterTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JCheckBox summaryCheckBox;
    // End of variables declaration//GEN-END:variables

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void initListeners() {
        filterTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                requestFiltering();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                requestFiltering();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }

        });
    }

    private void requestFiltering() {
        mFilterManager.setText(filterTextField.getText());
        mFilterManager.setFilterDescription(descriptionCheckBox.isSelected());
        mFilterManager.setFilterSummary(summaryCheckBox.isSelected());

        mFilterManager.requestFiltering();
    }

}
