/*
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui;

import java.util.Comparator;
import java.util.EnumSet;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import org.apache.commons.lang3.StringUtils;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import se.trixon.almond.util.swing.DelayedResetRunner;
import se.trixon.almond.util.swing.SwingHelper;
import se.trixon.sabas.Sabas;
import se.trixon.sabas.api.DictionarySection;
import se.trixon.sabas.api.Pkg;
import se.trixon.sabas.api.PkgDictionary;
import se.trixon.sabas.api.PkgStatus;
import se.trixon.sabas.core.PkgManager;
import se.trixon.sabas.ui.parts.ZebraListCellRenderer;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//se.trixon.sabas.ui//Filter//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "FilterTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "left", openAtStartup = true)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_FilterAction",
        preferredID = "FilterTopComponent"
)
@Messages({
    "CTL_FilterAction=Filter"
})
public final class FilterTopComponent extends TopComponent {

    private final PkgManager mPkgManager = PkgManager.getInstance();
    private final DelayedResetRunner mDelayedResetRunner;
    private final Set<Integer> mSelectedGroupIds = new HashSet<>();
    private final Set<Integer> mSelectedArchIds = new HashSet<>();
    private final Set<Integer> mSelectedRepositoryIds = new HashSet<>();
    private final Set<Integer> mSelectedVendorIds = new HashSet<>();
    private final Set<Integer> mSelectedPackagerIds = new HashSet<>();
    private Set<PkgStatus> mSelectedStatuses;

    public FilterTopComponent() {
        mDelayedResetRunner = new DelayedResetRunner(300, () -> {
            filter();
        });
        initComponents();
        setName(Bundle.CTL_FilterAction());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);
        setHtmlDisplayName("<html><b>%s</b></html>".formatted(getName()));

        var zebraRenderer = new ZebraListCellRenderer();
        archList.setCellRenderer(zebraRenderer);
        statusList.setCellRenderer(zebraRenderer);
        vendorList.setCellRenderer(zebraRenderer);
        packagerList.setCellRenderer(zebraRenderer);
        repositoryList.setCellRenderer(zebraRenderer);

        initListeners();

        tabbedPane.putClientProperty("JTabbedPane.tabRotation", "auto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean filterList(Set<Integer> set, int id) {
        return set.isEmpty() || set.contains(-1) || set.contains(id);
    }

    private void filter() {
        var filterStream = mPkgManager.getAllItems().stream()
                .filter(p -> {
                    if (mSelectedStatuses.isEmpty() || mSelectedStatuses.contains(PkgStatus.ALL)) {
                        return true;
                    }
                    if (p.isUpgradable() && mSelectedStatuses.contains(PkgStatus.UPGRADABLE)) {
                        return true;
                    }
                    if (p.isOrphaned() && mSelectedStatuses.contains(PkgStatus.ORPHANED)) {
                        return true;
                    }
                    if (p.isInstalled() && mSelectedStatuses.contains(PkgStatus.INSTALLED)) {
                        return true;
                    }

                    if (!p.isInstalled() && mSelectedStatuses.contains(PkgStatus.AVAILABLE)) {
                        return true;
                    }

                    return false;
                })
                .filter(p -> filterList(mSelectedArchIds, p.getArchId()))
                .filter(p -> filterList(mSelectedRepositoryIds, p.getRepositoryId()))
                .filter(p -> filterList(mSelectedVendorIds, p.getVendorId()))
                .filter(p -> filterList(mSelectedPackagerIds, p.getPackagerId()))
                .filter(p -> filterList(mSelectedGroupIds, p.getGroupId()));

        var text = filterTextField.getText();
        if (StringUtils.isNotBlank(text)) {
            var cleanInput = text.trim().toLowerCase();
            var tokens = StringUtils.split(cleanInput);
            var searchSummary = summaryCheckBox.isSelected();
            var searchDesc = descriptionCheckBox.isSelected();

            filterStream = filterStream
                    .filter(p -> FilterHelper.matchSplitFuzzy(
                            p.getNameLower(),
                            p.getSummaryLower(),
                            p.getDescriptionLower(),
                            tokens,
                            searchSummary,
                            searchDesc))
                    .map(p -> {
                        int score = FilterHelper.calculateRelevance(p.getNameLower(), cleanInput, tokens);
                        if (score == 4 && tokens.length > 0 && !p.getNameLower().contains(tokens[0])) {
                            score = 5;
                        }
                        return new WeightedPkg(p, score);
                    })
                    .sorted(Comparator
                            .comparingInt(WeightedPkg::relevance)
                            .thenComparing((w1, w2) -> w1.pkg().getName().compareToIgnoreCase(w2.pkg().getName()))
                    )
                    .map(WeightedPkg::pkg);
        }

        mPkgManager.setFilteredItems(filterStream.toList());
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterTextField = new javax.swing.JTextField();
        summaryCheckBox = new javax.swing.JCheckBox();
        descriptionCheckBox = new javax.swing.JCheckBox();
        resetButton = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        propertiesPanel = new javax.swing.JPanel();
        statusScrollPane = new javax.swing.JScrollPane();
        statusList = new javax.swing.JList<>();
        archScrollPane = new javax.swing.JScrollPane();
        archList = new javax.swing.JList<>();
        repositoryScrollPane = new javax.swing.JScrollPane();
        repositoryList = new javax.swing.JList<>();
        vendorScrollPane = new javax.swing.JScrollPane();
        vendorList = new javax.swing.JList<>();
        packagerScrollPane = new javax.swing.JScrollPane();
        packagerList = new javax.swing.JList<>();
        groupScrollPane = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList<>();

        org.openide.awt.Mnemonics.setLocalizedText(summaryCheckBox, org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.summaryCheckBox.text")); // NOI18N
        summaryCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryCheckBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(descriptionCheckBox, org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.descriptionCheckBox.text")); // NOI18N
        descriptionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionCheckBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(resetButton, org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.resetButton.text")); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        propertiesPanel.setLayout(new javax.swing.BoxLayout(propertiesPanel, javax.swing.BoxLayout.PAGE_AXIS));

        statusScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.statusScrollPane.border.title"))); // NOI18N

        statusList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                statusListValueChanged(evt);
            }
        });
        statusScrollPane.setViewportView(statusList);

        propertiesPanel.add(statusScrollPane);

        archScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.archScrollPane.border.title"))); // NOI18N
        archScrollPane.setViewportView(archList);

        propertiesPanel.add(archScrollPane);

        repositoryScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.repositoryScrollPane.border.title"))); // NOI18N
        repositoryScrollPane.setViewportView(repositoryList);

        propertiesPanel.add(repositoryScrollPane);

        vendorScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.vendorScrollPane.border.title"))); // NOI18N
        vendorScrollPane.setViewportView(vendorList);

        propertiesPanel.add(vendorScrollPane);

        packagerScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.packagerScrollPane.border.title"))); // NOI18N
        packagerScrollPane.setViewportView(packagerList);

        propertiesPanel.add(packagerScrollPane);

        tabbedPane.addTab(org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.propertiesPanel.TabConstraints.tabTitle"), propertiesPanel); // NOI18N

        groupScrollPane.setViewportView(groupList);

        tabbedPane.addTab(org.openide.util.NbBundle.getMessage(FilterTopComponent.class, "FilterTopComponent.groupScrollPane.TabConstraints.tabTitle"), groupScrollPane); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(summaryCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(descriptionCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetButton))
                            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summaryCheckBox)
                    .addComponent(descriptionCheckBox)
                    .addComponent(resetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listSelection(ListSelectionEvent event, DictionarySection dictionarySection, Set<Integer> set, JList<String> list) {
        if (!event.getValueIsAdjusting()) {
            var selectedTexts = list.getSelectedValuesList();
            set.clear();
            for (var text : selectedTexts) {
                int id = PkgDictionary.getInstance().getId(dictionarySection, text);
                if (id == -1) {
                    break;
                }
                set.add(id);
            }
            mDelayedResetRunner.reset();
        }
    }

    private void populateLists() {
        populateLists(groupList, DictionarySection.GROUP);
        populateLists(archList, DictionarySection.ARCH);
        populateLists(repositoryList, DictionarySection.REPOSITORY);
        populateLists(vendorList, DictionarySection.VENDOR);
        populateLists(packagerList, DictionarySection.PACKAGER);
        var statusModel = new DefaultListModel<PkgStatus>();
        statusModel.addAll(List.of(PkgStatus.values()));
        statusList.setModel(statusModel);
        statusList.setSelectedIndex(0);
    }

    private void populateLists(JList<String> list, DictionarySection dictionarySection) {
        var model = new DefaultListModel<String>();
        model.addElement("*");

        var allItems = PkgDictionary.getInstance().getAllValuesSorted(dictionarySection);
        model.addAll(allItems);

        list.setModel(model);
        list.setSelectedIndex(0);
    }

    private void summaryCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryCheckBoxActionPerformed
        mDelayedResetRunner.reset();
    }//GEN-LAST:event_summaryCheckBoxActionPerformed

    private void descriptionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionCheckBoxActionPerformed
        mDelayedResetRunner.reset();
    }//GEN-LAST:event_descriptionCheckBoxActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        filterTextField.setText("");
        List.of(
                summaryCheckBox,
                descriptionCheckBox)
                .forEach(cb -> cb.setSelected(false));

        List.of(statusList,
                archList,
                groupList,
                packagerList,
                repositoryList,
                vendorList)
                .forEach(list -> list.setSelectedIndex(0));
    }//GEN-LAST:event_resetButtonActionPerformed

    private void statusListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_statusListValueChanged
        if (!evt.getValueIsAdjusting()) {
            if (statusList.getSelectedValuesList().isEmpty()) {
                mSelectedStatuses.clear();
            } else {
                mSelectedStatuses = EnumSet.copyOf(statusList.getSelectedValuesList());
            }
            mDelayedResetRunner.reset();
        }
    }//GEN-LAST:event_statusListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> archList;
    private javax.swing.JScrollPane archScrollPane;
    private javax.swing.JCheckBox descriptionCheckBox;
    private javax.swing.JTextField filterTextField;
    private javax.swing.JList<String> groupList;
    private javax.swing.JScrollPane groupScrollPane;
    private javax.swing.JList<String> packagerList;
    private javax.swing.JScrollPane packagerScrollPane;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JList<String> repositoryList;
    private javax.swing.JScrollPane repositoryScrollPane;
    private javax.swing.JButton resetButton;
    private javax.swing.JList<PkgStatus> statusList;
    private javax.swing.JScrollPane statusScrollPane;
    private javax.swing.JCheckBox summaryCheckBox;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JList<String> vendorList;
    private javax.swing.JScrollPane vendorScrollPane;
    // End of variables declaration//GEN-END:variables

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void initListeners() {
        filterTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                mDelayedResetRunner.reset();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                mDelayedResetRunner.reset();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }

        });

        Sabas.getGlobalState().addListener(gsce -> {
            populateLists();
        }, PkgManager.KEY_ALL_ITEMS);

        groupList.addListSelectionListener(event -> {
            listSelection(event, DictionarySection.GROUP, mSelectedGroupIds, groupList);
        });

        archList.addListSelectionListener(event -> {
            listSelection(event, DictionarySection.ARCH, mSelectedArchIds, archList);
        });

        repositoryList.addListSelectionListener(event -> {
            listSelection(event, DictionarySection.REPOSITORY, mSelectedRepositoryIds, repositoryList);
        });

        vendorList.addListSelectionListener(event -> {
            listSelection(event, DictionarySection.VENDOR, mSelectedVendorIds, vendorList);
        });

        packagerList.addListSelectionListener(event -> {
            listSelection(event, DictionarySection.PACKAGER, mSelectedPackagerIds, packagerList);
        });

        Sabas.getGlobalState().addListener(gsce -> {
            SwingHelper.enableComponents(this, !gsce.<Boolean>getValue());
        }, PkgManager.KEY_TASK_RUNNING);
    }

    private record WeightedPkg(Pkg pkg, int relevance) {

    }

}
