/*
 * Copyright 2026 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.sabas.ui;

import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.SwingUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import se.trixon.almond.util.swing.DelayedResetRunner;
import se.trixon.almond.util.swing.SwingHelper;
import se.trixon.sabas.Sabas;
import se.trixon.sabas.api.Pkg;
import se.trixon.sabas.core.PkgManager;
import se.trixon.sabas.ui.parts.PkgRenderer;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//se.trixon.sabas.ui//Packages//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "PackagesTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "list", openAtStartup = true)
@ActionID(category = "Window", id = "se.trixon.sabas.ui.PackagesTopComponent")
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PackagesAction",
        preferredID = "PackagesTopComponent"
)
@Messages({
    "CTL_PackagesAction=Packages",
    "CTL_PackagesTopComponent=Packages"
})
public final class PackagesTopComponent extends BaseTopComponent {

    private final PkgListModel mPkgListModel;
    private final DelayedResetRunner mSelectDelayedResetRunner;

    public PackagesTopComponent() {
        initComponents();
        setName(Bundle.CTL_PackagesTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        mSelectDelayedResetRunner = new DelayedResetRunner(120, () -> {
            mPkgManager.setSelectedPkg(packagesList.getSelectedValue());
            updateFooter();
        });
        mPkgListModel = new PkgListModel(mPkgManager.getFilteredItems());
        packagesList.setModel(mPkgListModel);
        packagesList.setCellRenderer(new PkgRenderer());

        initListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packagesScrollPane = new javax.swing.JScrollPane();
        packagesList = new javax.swing.JList<>();
        footerLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        packagesScrollPane.setMinimumSize(new java.awt.Dimension(250, 23));
        packagesScrollPane.setPreferredSize(new java.awt.Dimension(300, 260));

        packagesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        packagesList.setMinimumSize(new java.awt.Dimension(300, 160));
        packagesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                packagesListValueChanged(evt);
            }
        });
        packagesScrollPane.setViewportView(packagesList);

        add(packagesScrollPane, java.awt.BorderLayout.CENTER);

        footerLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(footerLabel, "0/0"); // NOI18N
        add(footerLabel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void packagesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_packagesListValueChanged
        if (!evt.getValueIsAdjusting()) {
            mSelectDelayedResetRunner.reset();
        }
    }//GEN-LAST:event_packagesListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footerLabel;
    private javax.swing.JList<Pkg> packagesList;
    private javax.swing.JScrollPane packagesScrollPane;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void initListeners() {
        Sabas.getGlobalState().addListener(gsce -> {
            SwingUtilities.invokeLater(() -> {
                if (mPkgListModel != null) {
                    packagesList.clearSelection();
                    mPkgListModel.updateData();
                    if (mPkgListModel.getSize() > 0) {
                        packagesList.setSelectedIndex(0);
                    }
                }
                updateFooter();
            });
        }, PkgManager.KEY_FILTERED_ITEMS);

//        Sabas.getGlobalState().addListener(gsce -> {
//            displayPackageInfo(gsce.getValue());
//        }, PkgManager.KEY_SELECTED_PKG);
//
//        Sabas.getGlobalState().addListener(gsce -> {
//            if (mPkgManager.getSelectedPkg() == mPkgManager.getDetailedPkg()) {
//                displayPackageInfoDetails(gsce.getValue());
//            }
//        }, PkgManager.KEY_SELECTED_PKG_DETAILS);
        Sabas.getGlobalState().addListener(gsce -> {
            SwingHelper.enableComponents(this, !gsce.<Boolean>getValue());
        }, PkgManager.KEY_TASK_RUNNING);
    }

    private void updateFooter() {
        var selected = "";
        var selectedIndex = packagesList.getSelectedIndex();
        if (selectedIndex != -1) {
            selected = "@%,d/".formatted(selectedIndex + 1);
        }
        footerLabel.setText("%s%,d/%,d".formatted(
                selected,
                mPkgManager.getFilteredItems().size(),
                mPkgManager.getAllItems().size()
        ));
    }

    private static class PkgListModel extends AbstractListModel<Pkg> {

        private final List<? extends Pkg> sourceList;

        public PkgListModel(List<Pkg> filteredItems) {
            this.sourceList = filteredItems;
        }

        public void updateData() {
            fireContentsChanged(this, 0, Math.max(0, getSize() - 1));
        }

        @Override
        public int getSize() {
            return sourceList.size();
        }

        @Override
        public Pkg getElementAt(int index) {
            return sourceList.get(index);
        }
    }
}
